### PR TITLE
Fix infinte loop when using symlinks across mounts

### LINKED ISSUE #133: cd /soft/link/directory/from/other/mount/point end up in Infinite Loop
Need support for symlinked directory too. When you try to switch into a soft linked directory from other mount point it ends in an infinite loop and the terminal hangs until pressing ctrl + C.

eg: 
OS : Mac OSX
autoenv : 1.0.0
Shell : zsh
```
ln -s /Volumes/Disk1/code /Users/ashokraja/code
cd /Users/ashokraja/code/autoenv


df /Users/ashokraja/code
++ awk 'END{print $NF}'
++ _mountpoint=/Volumes/MDRIVE
++ _hadone=
++ '[' /Users/ashokraja/code '!=' /Volumes/Disk1 ']'
++ _file=/Users/ashokraja/code/.env
++ '[' -f /Users/ashokraja/code/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' /Users/ashokraja '!=' /Volumes/Disk1 ']'
++ _file=/Users/ashokraja/.env
++ '[' -f /Users/ashokraja/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' /Users '!=' /Volumes/Disk1 ']'
++ _file=/Users/.env
++ '[' -f /Users/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' / '!=' /Volumes/Disk1 ']'
++ _file=//.env
++ '[' -f //.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' / '!=' /Volumes/MDRIVE ']'
++ _file=//.env
++ '[' -f //.env ']'
++ command -v chdir
++ builtin cd ..
...
....
```
Infinite loop.

### PR DESCRIPTION
**Pull request by ashokrajar**
Closes #133

### CODE REVIEW

File: activate.sh [hunk 1]
```diff
@@ -4,10 +4,10 @@ AUTOENV_ENV_FILENAME="${AUTOENV_ENV_FILENAME:-.env}"
 autoenv_init() {
 	local _mountpoint _files _orderedfiles _sedregexp
 	if [ "${OSTYPE#darwin*}" != "${OSTYPE}" ]; then
-		_mountpoint="`df "${PWD}" | awk 'END{print $NF}'`"
+		_mountpoint="`df "$(pwd -P)" | awk 'END{print $NF}'`"
```
Comment (dasJ) [inline activate.sh]: No need for this call, df does this automatically

File: activate.sh [hunk 2]
```diff
@@ -4,10 +4,10 @@ AUTOENV_ENV_FILENAME="${AUTOENV_ENV_FILENAME:-.env}"
...
 		_sedregexp='-E'
 	else
-		_mountpoint="`stat -c '%m' \"${PWD}\"`"
+		_mountpoint="`stat -c '%m' \"$(pwd -P)\"`"
```
Comment (dasJ) [inline activate.sh]: Not sure about stat, but as it occurs on the Mac as well, I guess it resolves symlinks as well.

File: activate.sh [hunk 3]
```diff
@@ -17,8 +17,8 @@ autoenv_init() {
 	# We do this in a subshell so we can cd/chdir
 	_files="`
 		_hadone=''
-		while [ "${PWD}" != "${_mountpoint}" ]; do
-			_file="${PWD}/${AUTOENV_ENV_FILENAME}"
+		while [ "$(pwd -P)" != "${_mountpoint}" ]; do
+			_file="$(pwd -P)/${AUTOENV_ENV_FILENAME}"
```
Comment (dasJ) [inline activate.sh]: This can get wrong because the .env file might depend on being in the symlinked directory and not in the phsyical directory

File: activate.sh [hunk 4]
```diff
@@ -28,7 +28,7 @@ autoenv_init() {
 ${_file}"
 				fi
 			fi
-			command -v chdir >/dev/null 2>&1 && chdir .. || builtin cd ..
+			command -v chdir >/dev/null 2>&1 && chdir (pwd -P)/.. || builtin cd (pwd -P)/..
```
Comment (dasJ) [inline activate.sh]: Not sure about this, it might fix an issue we haven't found yet (initite looping), but it might also create new ones. I'll test this.

File: activate.sh (hunk 2 above)
Comment (ashokrajar) [inline activate.sh]: stat doesn't resolve the symlinks correctly for other mount points. So this fix is required.

File: activate.sh (hunk 1 above)
Comment (ashokrajar) [inline activate.sh]: Agree.

File: activate.sh (hunk 4 above)
Comment (dasJ) [inline activate.sh]: Result of tests: This seems to be correct.

File: activate.sh (hunk 3 above)
Comment (ashokrajar) [inline activate.sh]: If .env file exists in symlinked directory then it should exists on the original physical(filesystem) too. So I don't see any issue here and I have this code running in my system for almost a month now and have not noticed any issue at least on OSX.

Comment (dasJ) [inline activate.sh]: Love to hear that it works for you! If you could remove that one call for `df` and modify the changelog, I can merge it :+1:
